events {}

http {
  include /etc/nginx/mime.types;

  types {
    application/manifest+json webmanifest;
  }

  server {
    listen 80;
    root /usr/share/nginx/html;

    location / {
      try_files $uri $uri/ =404;
    }
  }
}
